version: '3.9'

services:
  db:
    image: mariadb:10.7 # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    container_name: wp-database
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST="%" # Apple M1 compatibility
    volumes:
      - ${DOCKER_PATH}/dbdata:/var/lib/mysql
    #platform: linux/amd64 # Apple M1 compatibility
    ports:
      - "${IP}:3306:3306" # change ip if required
    command: [
      '--default-authentication-plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - wordpress

  wordpress:
    # default port 9000 (FastCGI)
    depends_on:
      - db
    container_name: wp-wordpress
    build:
      context: ${DOCKER_PATH}
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      # For debugging only:
      - WORDPRESS_DEBUG=1
      - WORDPRESS_CONFIG_EXTRA=
          define( 'WP_REDIS_HOST', 'redis' );
          define( 'WP_REDIS_PORT', 6379 );
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${DOCKER_PATH}/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    networks:
      - wordpress

  wpcli:
    image: wordpress:cli
    container_name: wpcli
    volumes:
      - ${DOCKER_PATH}/config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
    entrypoint: wp
    command: "--info"
    environment:
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=db:3306
    depends_on:
      - db
      - wordpress
    networks:
      - wordpress

  webserver:
    # default ports 80, 443 - expose mapping as needed to host
    depends_on:
      - wordpress
    image: nginx:1
    container_name: wp-nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${DOCKER_PATH}/config/nginx-conf/conf:/etc/nginx/conf.d/:ro
      - ${DOCKER_PATH}/config/nginx-conf/ssl:/etc/ssl/:ro
      - ${NGINX_LOGS}:/var/log/nginx
    networks:
      - wordpress

  pma:
    image: phpmyadmin:latest
    container_name: wp-phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 300M
    ports:
      - "${IP}:8181:80"
    networks:
      - wordpress

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
      - --maxmemory 128mb
      - --maxmemory-policy allkeys-lru
    volumes:
      - ${DOCKER_PATH}/redis:/var/lib/redis
      - ${DOCKER_PATH}/redis:/data
      #- ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - wordpress

volumes:
  wordpress:
  dbdata:
  redis:

networks:
  wordpress:
    name: wp-wordpress
    driver: bridge
